# Generated by Django 3.2.3 on 2021-06-02 17:04

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Topluluk Adı')),
                ('numUsers', models.IntegerField(verbose_name='Kullanıcı Sayısı')),
                ('numPosts', models.IntegerField(verbose_name='Post Sayısı')),
                ('isPrivate', models.BooleanField(verbose_name='Private mı?')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('joinedUsers', models.ManyToManyField(related_name='joinedCommunities', to='person.Person')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=builtins.max, verbose_name='Description')),
                ('data_field_temps', models.JSONField(default='{}', max_length=builtins.max, verbose_name='DataFieldTemps')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='mainapp.community')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('posterid', models.IntegerField()),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=builtins.max, verbose_name='Description')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('dataFields', models.JSONField(default='{}', max_length=builtins.max, verbose_name='Data')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.community')),
                ('postTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.posttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DataFieldTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('form_content', models.JSONField(default={}, max_length=builtins.max, verbose_name='Data')),
                ('postTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.posttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('content', models.JSONField(default={}, max_length=builtins.max, verbose_name='Data')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
            ],
        ),
    ]
