# Generated by Django 3.2.4 on 2021-06-07 08:58

import builtins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dataFields',
        ),
        migrations.RemoveField(
            model_name='posttemplate',
            name='data_field_temps',
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=builtins.max, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafield',
            name='content',
            field=models.JSONField(max_length=builtins.max, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataFields', to='mainapp.post'),
        ),
        migrations.AlterField(
            model_name='datafieldtemp',
            name='form_content',
            field=models.JSONField(max_length=builtins.max, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='datafieldtemp',
            name='postTemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataFieldTemplates', to='mainapp.posttemplate'),
        ),
    ]
