# Generated by Django 3.2.3 on 2021-06-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Topluluk Adı')),
                ('numUsers', models.IntegerField(verbose_name='Kullanıcı Sayısı')),
                ('numPosts', models.IntegerField(verbose_name='Post Sayısı')),
                ('isPrivate', models.BooleanField(verbose_name='Private mı?')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='community.user')),
            ],
        ),
    ]
