# Generated by Django 3.2.3 on 2021-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='numPosts',
            field=models.IntegerField(verbose_name='Post Sayısı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kullanıcı Adı'),
        ),
    ]
