# Generated by Django 3.2.9 on 2021-11-05 18:40

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Topluluk Adı')),
                ('description', models.TextField(max_length=builtins.max, verbose_name='Description')),
                ('numUsers', models.IntegerField(verbose_name='Kullanıcı Sayısı')),
                ('numPosts', models.IntegerField(verbose_name='Post Sayısı')),
                ('isPrivate', models.BooleanField(verbose_name='Private mı?')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=builtins.max, verbose_name='Description')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='protopost.community')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('posterid', models.IntegerField()),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=builtins.max, verbose_name='Description')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='protopost.community')),
                ('postTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protopost.posttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DataFieldTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('form_content', models.JSONField(max_length=builtins.max, verbose_name='Data')),
                ('postTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataFieldTemplates', to='protopost.posttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('content', models.JSONField(max_length=builtins.max, verbose_name='Data')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataFields', to='protopost.post')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='joinedUsers',
            field=models.ManyToManyField(related_name='joinedCommunities', to='protopost.User'),
        ),
        migrations.AddField(
            model_name='community',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='protopost.user'),
        ),
    ]
