# Generated by Django 3.2.9 on 2021-11-10 07:54

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protopost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='community',
            name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='community',
            name='joinedUsers',
        ),
        migrations.RemoveField(
            model_name='community',
            name='numPosts',
        ),
        migrations.RemoveField(
            model_name='community',
            name='numUsers',
        ),
        migrations.RemoveField(
            model_name='datafieldtemp',
            name='postTemplate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postTemplate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posterid',
        ),
        migrations.AddField(
            model_name='community',
            name='community_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='joined_users',
            field=models.ManyToManyField(related_name='joined_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datafieldtemp',
            name='post_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_field_templates', to='protopost.posttemplate'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protopost.posttemplate'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=builtins.max),
        ),
        migrations.AlterField(
            model_name='community',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='protopost.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='protopost.community'),
        ),
        migrations.AlterField(
            model_name='posttemplate',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='protopost.community'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
