version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: ''
       MYSQL_USER: ''
       MYSQL_PASSWORD: ''
       MYSQL_ROOT_PASSWORD: ''
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/protopost-backend
    ports:
      - "8000:8000"
    depends_on:
      - db