# I created this docker-compose file based on this article https://medium.com/@minghz42/docker-setup-for-django-on-mysql-1f063c9d16a0
version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: ''
       MYSQL_USER: ''
       MYSQL_PASSWORD: ''
       MYSQL_ROOT_PASSWORD: ''
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/protopost-backend
    ports:
      - "7000:7000"
    depends_on:
      - db
