# Generated by Django 3.2.4 on 2021-06-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210607_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('descr', models.CharField(max_length=300, verbose_name='Descr')),
                ('url', models.CharField(max_length=300, verbose_name='Link')),
                ('url_to_img', models.CharField(max_length=300, verbose_name='Img_link')),
            ],
        ),
    ]
