# Generated by Django 3.2.4 on 2021-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=2, verbose_name='Country Code')),
            ],
            options={
                'ordering': ['userid'],
            },
        ),
    ]
