# Generated by Django 3.2.3 on 2021-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Ünvan')),
                ('firstname', models.CharField(max_length=50, verbose_name='Ad')),
                ('lastname', models.CharField(max_length=50, verbose_name='Soyad')),
                ('location', models.CharField(max_length=50, verbose_name='Konum')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('age', models.IntegerField(verbose_name='Yaş')),
                ('phone', models.CharField(max_length=12, verbose_name='Telefon')),
                ('imageUrl', models.CharField(max_length=250, verbose_name='Resim')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
